# CI and PR triggers
trigger:
- master
pr:
- master



jobs:
- job: Windows
  pool:
    vmImage: windows-2019
    
  steps:
   - task: UseDotNet@3
     displayName: 'Use .NET Core sdk'
     inputs:
       packageType: sdk
       version: 3.0.0-preview6
       installationPath: $(Agent.ToolsDirectory)/dotnet
   - script: build.cmd
